import {
  bigint,
  boolean,
  doublePrecision,
  index,
  integer,
  pgTable,
  text,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const marketDataOrderBookSnapshotsTable = pgTable(
  "market_data_order_book_snapshots",
  {
    id: text("id").notNull(),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    exchangeTime: bigint("exchange_time", { mode: "number" }),
    receivedAt: bigint("received_at", { mode: "number" }).notNull(),
    depth: integer("depth").notNull(),
    bestBidPrice: doublePrecision("best_bid_price").notNull(),
    bestBidSize: doublePrecision("best_bid_size").notNull(),
    bestAskPrice: doublePrecision("best_ask_price").notNull(),
    bestAskSize: doublePrecision("best_ask_size").notNull(),
    midPrice: doublePrecision("mid_price").notNull(),
    microPrice: doublePrecision("micro_price"),
    vampPrice: doublePrecision("vamp_price"),
    spreadBps: doublePrecision("spread_bps").notNull(),
    bidsJson: text("bids_json").notNull(),
    asksJson: text("asks_json").notNull(),
    sequence: text("sequence"),
    rawJson: text("raw_json"),
  },
  (table) => [
    uniqueIndex("md_book_id_received_at_idx").on(table.id, table.receivedAt),
    index("md_book_venue_symbol_received_at_idx").on(table.venue, table.symbol, table.receivedAt),
    index("md_book_symbol_received_at_idx").on(table.symbol, table.receivedAt),
  ],
);

export const marketDataTradesTable = pgTable(
  "market_data_trades",
  {
    id: text("id").notNull(),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    tradeId: text("trade_id"),
    exchangeTime: bigint("exchange_time", { mode: "number" }),
    receivedAt: bigint("received_at", { mode: "number" }).notNull(),
    price: doublePrecision("price").notNull(),
    quantity: doublePrecision("quantity").notNull(),
    side: text("side"),
    aggressorSide: text("aggressor_side"),
    rawJson: text("raw_json"),
  },
  (table) => [
    uniqueIndex("md_trades_id_received_at_idx").on(table.id, table.receivedAt),
    index("md_trades_venue_symbol_received_at_idx").on(table.venue, table.symbol, table.receivedAt),
    index("md_trades_symbol_received_at_idx").on(table.symbol, table.receivedAt),
    uniqueIndex("md_trades_venue_trade_id_received_at_idx").on(
      table.venue,
      table.tradeId,
      table.receivedAt,
    ),
  ],
);

export const marketDataTickersTable = pgTable(
  "market_data_tickers",
  {
    id: text("id").notNull(),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    exchangeTime: bigint("exchange_time", { mode: "number" }),
    receivedAt: bigint("received_at", { mode: "number" }).notNull(),
    markPrice: doublePrecision("mark_price"),
    indexPrice: doublePrecision("index_price"),
    lastPrice: doublePrecision("last_price"),
    fundingRate: doublePrecision("funding_rate"),
    openInterest: doublePrecision("open_interest"),
    rawJson: text("raw_json"),
  },
  (table) => [
    uniqueIndex("md_tickers_id_received_at_idx").on(table.id, table.receivedAt),
    index("md_tickers_venue_symbol_received_at_idx").on(
      table.venue,
      table.symbol,
      table.receivedAt,
    ),
    index("md_tickers_symbol_received_at_idx").on(table.symbol, table.receivedAt),
  ],
);

export const botRunsTable = pgTable("bot_runs", {
  id: text("id").primaryKey(),
  mode: text("mode").notNull(),
  venue: text("venue").notNull(),
  symbol: text("symbol").notNull(),
  strategyName: text("strategy_name").notNull(),
  strategyVersion: text("strategy_version"),
  configHash: text("config_hash").notNull(),
  configJson: text("config_json").notNull(),
  gitSha: text("git_sha"),
  gitDirty: boolean("git_dirty").notNull().default(false),
  startedAt: bigint("started_at", { mode: "number" }).notNull(),
  endedAt: bigint("ended_at", { mode: "number" }),
  status: text("status").notNull(),
  stopReason: text("stop_reason"),
  metadataJson: text("metadata_json"),
});

export const botMarketObservationsTable = pgTable(
  "bot_market_observations",
  {
    id: text("id").notNull(),
    runId: text("run_id").notNull(),
    observedAt: bigint("observed_at", { mode: "number" }).notNull(),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    latestBookSnapshotId: text("latest_book_snapshot_id"),
    latestTickerId: text("latest_ticker_id"),
    latestTradeId: text("latest_trade_id"),
    localMid: doublePrecision("local_mid"),
    localMicro: doublePrecision("local_micro"),
    localVamp: doublePrecision("local_vamp"),
    markPrice: doublePrecision("mark_price"),
    externalFair: doublePrecision("external_fair"),
    externalAgeMs: bigint("external_age_ms", { mode: "number" }),
    externalDiffBps: doublePrecision("external_diff_bps"),
    positionQty: doublePrecision("position_qty"),
    inventoryNotional: doublePrecision("inventory_notional"),
    contextJson: text("context_json"),
  },
  (table) => [
    uniqueIndex("bot_obs_id_observed_at_idx").on(table.id, table.observedAt),
    index("bot_obs_run_observed_at_idx").on(table.runId, table.observedAt),
    index("bot_obs_run_symbol_observed_at_idx").on(table.runId, table.symbol, table.observedAt),
  ],
);

export const botQuoteDecisionsTable = pgTable(
  "bot_quote_decisions",
  {
    id: text("id").notNull(),
    runId: text("run_id").notNull(),
    observationId: text("observation_id"),
    decidedAt: bigint("decided_at", { mode: "number" }).notNull(),
    quoteCycleId: text("quote_cycle_id"),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    fairPrice: doublePrecision("fair_price").notNull(),
    reservationPrice: doublePrecision("reservation_price"),
    referencePrice: doublePrecision("reference_price"),
    sigma: doublePrecision("sigma"),
    gamma: doublePrecision("gamma"),
    kappa: doublePrecision("kappa"),
    inventoryQty: doublePrecision("inventory_qty"),
    inventorySkewBps: doublePrecision("inventory_skew_bps"),
    bidPrice: doublePrecision("bid_price"),
    bidSize: doublePrecision("bid_size"),
    askPrice: doublePrecision("ask_price"),
    askSize: doublePrecision("ask_size"),
    bidEnabled: boolean("bid_enabled").notNull().default(true),
    askEnabled: boolean("ask_enabled").notNull().default(true),
    spreadBps: doublePrecision("spread_bps"),
    halfSpreadBps: doublePrecision("half_spread_bps"),
    reason: text("reason"),
    decisionJson: text("decision_json"),
  },
  (table) => [
    uniqueIndex("bot_quotes_id_decided_at_idx").on(table.id, table.decidedAt),
    index("bot_quotes_run_decided_at_idx").on(table.runId, table.decidedAt),
    index("bot_quotes_run_symbol_decided_at_idx").on(table.runId, table.symbol, table.decidedAt),
  ],
);

export const botOrdersTable = pgTable(
  "bot_orders",
  {
    id: text("id").notNull(),
    runId: text("run_id").notNull(),
    quoteDecisionId: text("quote_decision_id"),
    createdAt: bigint("created_at", { mode: "number" }).notNull(),
    submittedAt: bigint("submitted_at", { mode: "number" }),
    acceptedAt: bigint("accepted_at", { mode: "number" }),
    canceledAt: bigint("canceled_at", { mode: "number" }),
    rejectedAt: bigint("rejected_at", { mode: "number" }),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    clientOrderId: text("client_order_id"),
    venueOrderId: text("venue_order_id"),
    side: text("side").notNull(),
    orderType: text("order_type").notNull(),
    price: doublePrecision("price"),
    quantity: doublePrecision("quantity").notNull(),
    postOnly: boolean("post_only"),
    reduceOnly: boolean("reduce_only"),
    timeInForce: text("time_in_force"),
    status: text("status").notNull(),
    reason: text("reason"),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    rawJson: text("raw_json"),
  },
  (table) => [
    uniqueIndex("bot_orders_id_created_at_idx").on(table.id, table.createdAt),
    index("bot_orders_run_created_at_idx").on(table.runId, table.createdAt),
    index("bot_orders_run_client_order_id_idx").on(table.runId, table.clientOrderId),
    index("bot_orders_run_venue_order_id_idx").on(table.runId, table.venueOrderId),
  ],
);

export const botFillsTable = pgTable(
  "bot_fills",
  {
    id: text("id").notNull(),
    runId: text("run_id").notNull(),
    orderId: text("order_id"),
    quoteDecisionId: text("quote_decision_id"),
    venue: text("venue").notNull(),
    symbol: text("symbol").notNull(),
    venueFillId: text("venue_fill_id"),
    venueOrderId: text("venue_order_id"),
    clientOrderId: text("client_order_id"),
    filledAt: bigint("filled_at", { mode: "number" }).notNull(),
    receivedAt: bigint("received_at", { mode: "number" }),
    side: text("side").notNull(),
    price: doublePrecision("price").notNull(),
    quantity: doublePrecision("quantity").notNull(),
    fee: doublePrecision("fee"),
    feeAsset: text("fee_asset"),
    liquidity: text("liquidity"),
    rawJson: text("raw_json"),
  },
  (table) => [
    uniqueIndex("bot_fills_id_filled_at_idx").on(table.id, table.filledAt),
    index("bot_fills_run_filled_at_idx").on(table.runId, table.filledAt),
    index("bot_fills_run_symbol_filled_at_idx").on(table.runId, table.symbol, table.filledAt),
    index("bot_fills_venue_fill_id_idx").on(table.venue, table.venueFillId),
  ],
);
