import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";

export interface CoverageMetric {
  covered: number;
  total: number;
  percent: number;
}

export interface CoverageFileSummary {
  file: string;
  lines: CoverageMetric;
  functions: CoverageMetric;
  branches: CoverageMetric;
}

export interface CoverageSummary {
  totals: {
    lines: CoverageMetric;
    functions: CoverageMetric;
    branches: CoverageMetric;
  };
  files: CoverageFileSummary[];
}

interface MutableFileSummary {
  file: string;
  linesTotal: number;
  linesCovered: number;
  functionsTotal: number;
  functionsCovered: number;
  branchesTotal: number;
  branchesCovered: number;
}

interface GenerateCoverageSummaryOptions {
  lcovPath?: string;
  outputPath?: string;
}

const DEFAULT_LCOV_PATH = "docs/coverage/lcov.info";
const DEFAULT_OUTPUT_PATH = "docs/coverage/summary.md";
const LOWEST_SOURCE_FILE_LIMIT = 10;

export function parseLcov(lcovText: string, cwd = process.cwd()): CoverageSummary {
  const files = lcovText
    .split("end_of_record")
    .map((record) => parseRecord(record, cwd))
    .filter((summary): summary is CoverageFileSummary => summary !== null);

  return {
    totals: {
      lines: sumMetric(files.map((file) => file.lines)),
      functions: sumMetric(files.map((file) => file.functions)),
      branches: sumMetric(files.map((file) => file.branches)),
    },
    files,
  };
}

export function formatCoverageSummary(summary: CoverageSummary): string {
  const lowestSourceFiles = summary.files
    .filter((file) => file.file.startsWith("src/"))
    .sort((a, b) => a.lines.percent - b.lines.percent || a.file.localeCompare(b.file))
    .slice(0, LOWEST_SOURCE_FILE_LIMIT);
  const totalRows = [
    [
      "Lines",
      summary.totals.lines.covered.toString(),
      summary.totals.lines.total.toString(),
      formatPercent(summary.totals.lines.percent),
    ],
    [
      "Functions",
      summary.totals.functions.covered.toString(),
      summary.totals.functions.total.toString(),
      formatPercent(summary.totals.functions.percent),
    ],
    [
      "Branches",
      summary.totals.branches.covered.toString(),
      summary.totals.branches.total.toString(),
      formatPercent(summary.totals.branches.percent),
    ],
  ];
  const lowestRows =
    lowestSourceFiles.length === 0
      ? [["No `src/` files found in LCOV.", "-", "-", "-"]]
      : lowestSourceFiles.map((file) => [
          `\`${file.file}\``,
          formatMetric(file.lines),
          formatMetric(file.functions),
          formatMetric(file.branches),
        ]);

  return `# Coverage Summary

Generated by \`bun run test:coverage\`.

## Totals

${formatMarkdownTable(["Metric", "Covered", "Total", "Coverage"], totalRows, [
  "left",
  "right",
  "right",
  "right",
])}

## Lowest Covered Source Files

${formatMarkdownTable(["File", "Lines", "Functions", "Branches"], lowestRows, [
  "left",
  "right",
  "right",
  "right",
])}
`;
}

export async function generateCoverageSummary(
  options: GenerateCoverageSummaryOptions = {},
): Promise<CoverageSummary> {
  const lcovPath = options.lcovPath ?? DEFAULT_LCOV_PATH;
  const outputPath = options.outputPath ?? DEFAULT_OUTPUT_PATH;
  const lcovText = await readFile(lcovPath, "utf8");
  const summary = parseLcov(lcovText);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, formatCoverageSummary(summary));
  return summary;
}

function parseRecord(record: string, cwd: string): CoverageFileSummary | null {
  const mutable: MutableFileSummary = {
    file: "",
    linesTotal: 0,
    linesCovered: 0,
    functionsTotal: 0,
    functionsCovered: 0,
    branchesTotal: 0,
    branchesCovered: 0,
  };

  for (const rawLine of record.split("\n")) {
    const line = rawLine.trim();
    if (line.length === 0) {
      continue;
    }
    if (line.startsWith("SF:")) {
      mutable.file = normalizeCoveragePath(line.slice(3), cwd);
      continue;
    }
    applyMetricLine(mutable, line);
  }

  if (mutable.file.length === 0) {
    return null;
  }

  return {
    file: mutable.file,
    lines: toMetric(mutable.linesCovered, mutable.linesTotal),
    functions: toMetric(mutable.functionsCovered, mutable.functionsTotal),
    branches: toMetric(mutable.branchesCovered, mutable.branchesTotal),
  };
}

function applyMetricLine(summary: MutableFileSummary, line: string): void {
  if (line.startsWith("LF:")) {
    summary.linesTotal = parseCount(line.slice(3));
    return;
  }
  if (line.startsWith("LH:")) {
    summary.linesCovered = parseCount(line.slice(3));
    return;
  }
  if (line.startsWith("FNF:")) {
    summary.functionsTotal = parseCount(line.slice(4));
    return;
  }
  if (line.startsWith("FNH:")) {
    summary.functionsCovered = parseCount(line.slice(4));
    return;
  }
  if (line.startsWith("BRF:")) {
    summary.branchesTotal = parseCount(line.slice(4));
    return;
  }
  if (line.startsWith("BRH:")) {
    summary.branchesCovered = parseCount(line.slice(4));
  }
}

function normalizeCoveragePath(path: string, cwd: string): string {
  if (!path.startsWith("/")) {
    return path;
  }
  const relativePath = relative(cwd, path);
  return relativePath.startsWith("..") ? path : relativePath;
}

function parseCount(value: string): number {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : 0;
}

function sumMetric(metrics: CoverageMetric[]): CoverageMetric {
  const covered = metrics.reduce((sum, metric) => sum + metric.covered, 0);
  const total = metrics.reduce((sum, metric) => sum + metric.total, 0);
  return toMetric(covered, total);
}

function toMetric(covered: number, total: number): CoverageMetric {
  return {
    covered,
    total,
    percent: total === 0 ? 100 : (covered / total) * 100,
  };
}

function formatMetric(metric: CoverageMetric): string {
  return `${metric.covered}/${metric.total} (${formatPercent(metric.percent)})`;
}

function formatPercent(percent: number): string {
  return `${percent.toFixed(1)}%`;
}

function formatMarkdownTable(
  headers: string[],
  rows: string[][],
  alignments: Array<"left" | "right">,
): string {
  const widths = headers.map((header, columnIndex) =>
    Math.max(header.length, ...rows.map((row) => row[columnIndex]?.length ?? 0), 3),
  );
  const renderRow = (cells: string[]) =>
    `| ${cells
      .map((cell, columnIndex) => {
        const width = widths[columnIndex] ?? cell.length;
        return alignments[columnIndex] === "right" ? cell.padStart(width) : cell.padEnd(width);
      })
      .join(" | ")} |`;
  const renderSeparator = () =>
    `| ${widths
      .map((width, columnIndex) => {
        if (alignments[columnIndex] === "right") {
          return `${"-".repeat(Math.max(3, width - 1))}:`;
        }
        return "-".repeat(width);
      })
      .join(" | ")} |`;

  return [renderRow(headers), renderSeparator(), ...rows.map(renderRow)].join("\n");
}
